services:
  - type: web
    name: nailvital-backend
    env: python
    rootDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: static
    name: nailvital-landing
    env: static
    buildCommand: ""
    publishDir: landing
