@echo off
echo Starting NailVital AI Backend...
echo 1. Making sure database 'nailvital' exists...
python setup_local_db.py
echo 2. Starting Uvicorn Server...
python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
pause
